# Data Science Academy

### Fundamentos de Linguagem Python para Análise de Dados e Data Science

##### Matemática e Manipulação de Matrizes com NumPy

In [1]:
# Versão da Linguagem Python 
from platform import python_version
print(python_version())

3.11.7


#### **Numpy**
- https://numpy.org

In [2]:
import numpy as np # type: ignore

In [3]:
np.__version__

'1.26.4'

##### Criando Arrays NumPy

In [4]:
# Array criado a partur de uma lista Python
arr1 = np.array([10,21,32,43,48,15,76,57,89])

In [5]:
print(arr1)

[10 21 32 43 48 15 76 57 89]


In [6]:
# Um objeto do tipo ndarray é um recipiente multidimensional de itens do mesmo tipo e tamanho
type(arr1)

numpy.ndarray

In [7]:
# Verificando o formato do Array
arr1.shape

(9,)

- Um array NumPy é uma estrutura de dados multidimensional usada em computação científica e análise de dados. O numPy fornece um objeto de matriz N-dimensional (ou ndarray), que é uma grade homogênea de elementos, geralmente números, que podem ser indexados por um conjunto de inteiros.
- Os arrays NumPy são mais eficientes do que as listas python para armazenar e manipular grandes quantidades de dados, pois são implementados em Linguagem C e fornecem várias otimizações de desempenho. Além disso, o NumPy permite a fácil leitura e escrita de arquivos de dados, integração com outras bibliotecas Python e suporte a operações em paralelo uando várias CPUs ou GPUs.

##### Indexação em Array NumPy

In [8]:
print(arr1)

[10 21 32 43 48 15 76 57 89]


In [9]:
# Imprimindo um elemento específico no array
arr1[4]

48

In [10]:
# Indexação
arr1[1:4]

array([21, 32, 43])

In [11]:
arr1[1:4+1]

array([21, 32, 43, 48])

In [12]:
# Cria uma lista de índices
indices = [1,2,5,6]

In [13]:
# Imprimindo os elementos dos índices
arr1[indices]

array([21, 32, 15, 76])

In [14]:
# Cria uma máscara booleana para os elementos pares
mask = (arr1 % 2 == 0)

In [15]:
arr1[mask]

array([10, 32, 48, 76])

In [16]:
# Alterando um elemento do array
arr1[0] = 100

In [17]:
print(arr1)

[100  21  32  43  48  15  76  57  89]


In [18]:
# Não é possível incluir elemento de outro tipo
try:
    arr1[0] = 'novo elemento'
except:
    print('Operação não permitida')

Operação não permitida


##### Funções NumPy

In [19]:
# A função np.array() cria um array NumPy
arr2 = np.array([1,2,3,4,5])

In [20]:
print(arr2)

[1 2 3 4 5]


In [21]:
# Verificando o tipo do objeto
type(arr2)

numpy.ndarray

In [22]:
# Digite . e pressione a tecla Tab no seu teclado para visualizar os métodos disponíveis em objetos NumPy
arr2

array([1, 2, 3, 4, 5])

In [23]:
# Usando métodos do Array NumPy
arr2.cumsum()

array([ 1,  3,  6, 10, 15])

In [24]:
arr2.cumprod()

array([  1,   2,   6,  24, 120])

In [25]:
# A função arange cria um array NumPy contendo uma progressão aritmética a partir de um intervalo - star, stop, step 
arr3 = np.arange(0,50,2)

In [26]:
print(arr3)    

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48]


In [27]:
type(arr3)

numpy.ndarray

In [28]:
np.shape(arr3)

(25,)

In [29]:
print(arr3.dtype)

int32


In [30]:
# Cria um array preenchido com zeros
arr4 = np.zeros(10)

In [31]:
arr4

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [32]:
# Retorna 1 nas posições em diagonal e o 0 no restante 
arr5 = np.eye(3)

In [33]:
print(arr5)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [34]:
# Os valores passados como parâmetro, formam uma diagonal
arr6 = np.diag(np.array([1,2,3,4]))

In [35]:
print(arr6)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [36]:
# Array de valores booleanos
arr7 = np.array([True, False, False, True])

In [37]:
print(arr7)

[ True False False  True]


In [38]:
# Array de strings
arr8 = np.array(['Linguagem Python', 'Linguagem R', 'Linguagem Julia'])

In [39]:
arr8

array(['Linguagem Python', 'Linguagem R', 'Linguagem Julia'], dtype='<U16')

A função linespace() do NumPy é usada para criar uma sequência de números igualmente espaçados dentro de um intervalo especificado. Esa função é amplamente utilizada em programação científica e matemática para gerar arrays de números para diversos fins, como gráficos, cálculos e simulações. 
O método linspace (linearly spaced vector) retorna um número de valores igualmente distribuídos no intervalo esepcificado.

In [40]:
print(np.linspace(0,10))

[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]


In [41]:
print(np.linspace(0,10,15))

[ 0.          0.71428571  1.42857143  2.14285714  2.85714286  3.57142857
  4.28571429  5.          5.71428571  6.42857143  7.14285714  7.85714286
  8.57142857  9.28571429 10.        ]


A função  logspace() no NumPy é usada para criar uma sequência de números igulmente espaçados em escala logarítmica dentro de um intervalor especificado. Essa função é aplamente utilizada em programação cienctífica e matemática para gerar arrays de números para diversos fins, como gráficos, cálculos e simulações.

In [42]:
print(np.logspace(0,5,10))

[1.00000000e+00 3.59381366e+00 1.29154967e+01 4.64158883e+01
 1.66810054e+02 5.99484250e+02 2.15443469e+03 7.74263683e+03
 2.78255940e+04 1.00000000e+05]


##### Manipulando Matrizes

In [44]:
# Criando uma matriz 
arr9 = np.array([[1,2,3],[9,8,7]])

In [46]:
type(arr9)

numpy.ndarray

In [47]:
print(arr9)

[[1 2 3]
 [9 8 7]]


In [52]:
# Criando uma matriz 2x3 apenas com números
arr10 = np.ones((2,3))

In [53]:
arr10

array([[1., 1., 1.],
       [1., 1., 1.]])

In [54]:
# Criando uma lista de listas 
lista = [[13,81,22],[0,34,59],[21,48,94]]

In [55]:
# a função matrix cria uma matriz a partir de uma lista de listas
arr11 = np.matrix(lista)

In [56]:
arr11

matrix([[13, 81, 22],
        [ 0, 34, 59],
        [21, 48, 94]])

In [57]:
type(arr11)

numpy.matrix

In [59]:
# Formato da matriz
np.shape(arr11)

(3, 3)

In [60]:
# Tamanho da matriz 
arr11.size

9

In [62]:
print(arr11.dtype)

int32


In [64]:
# Indexação de matrizes, lembrando que indexação em Python se incia em ZERO
arr11[2,1]

48

In [68]:
# Indexação em matrizes
arr11[0:2,2]

matrix([[22],
        [59]])

In [73]:
# Imprime todos os valores na linha. 
arr11[1,]

matrix([[ 0, 34, 59]])

In [74]:
# Alterando um elemento da matriz
arr11[1,0] = 100

In [75]:
print(arr11)

[[ 13  81  22]
 [100  34  59]
 [ 21  48  94]]


In [80]:
x = np.array([1,2]) # NumPy decide o tipo dos dados  
y = np.array([3.4,3.0]) # NumPy decide o tipo dos dados
z = np.array([1,2], dtype = np.float64) # Forçamos um tipo de dado particular 

In [81]:
print(x.dtype, y.dtype, z.dtype)

int32 float64 float64


In [82]:
arr12 = np.array([[24,76,92,14],[47,35,89,2]], dtype = float)

In [83]:
print(arr12)

array([[24., 76., 92., 14.],
       [47., 35., 89.,  2.]])

- O item size de um array numpy é atributo que retorna o tamanho em bytes de cada elemento do array. Em outras palavras, o item size representa o número de bytes necessários para armazenar cada valor do array numpy.

In [84]:
arr12.itemsize

8

In [85]:
arr12.nbytes

64

In [86]:
arr12.ndim

2

##### Manipulando Objetos de 3 e 4 dimensões com NumPy

In [87]:
# Cria uma array numpy em 3 dimensões
arr_3d = np.array([
    [
        [1,2,3,4],
        [5,6,7,8],
        [9,10,11,12]
    ],
    [
        [13,14,15,16],
        [17,18,19,20],
        [21,22,23,24]        
    ]
    ])

In [88]:
arr_3d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [90]:
type(arr_3d)

numpy.ndarray

In [91]:
arr_3d.ndim

3

In [92]:
arr_3d.shape

(2, 3, 4)

In [93]:
arr_3d[0,2,1]

10